# # # # # # a=range(1,51)
# # # # # # print(list(a))
# # # # # # print(tuple(a))
# # # # # # print(set(a))
# # # # # # ****************************************************
# # # # # a=range(51,1,-2)
# # # # # print(list(a))
# # # # a=range(-1,-111,-2)
# # # # print(tuple(a))
# # # a=range(-6,-9,-1)
# # # print(list(a))
# # # print("************")
# b=range(-6,-5)
# print(tuple(b))
# # a=range(2,3)
# # print(list(a))
a=range(2,20+1,2)
print(list(a))